sigafo/urls.py
#
# Sigafo main URLS
#
#
from django.conf.urls import patterns, include, url
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib import admin
from djgeojson.views import GeoJSONLayerView
from sigafo.contact.models import Contact
from sigafo.parc.models import Parcel, Block, Site
from sigafo.map.models import Map
from sigafo.parc.views import HomepageView
from sigafo.projet.models import Projet
from sigafo.utils.view_mixins import DetailProtected, ListProtected
from sigafo.projet import views
from sigafo.map import views as mapviews
from sigafo.parc import views as parcviews
from sigafo.contact import views as contactviews
from sigafo.referentiel import views as refviews
from sigafo.referentiel import models as modref

from sigafo.referentiel import serializers as ref_ser

from rest_framework import routers, serializers, viewsets
from rest_framework import permissions


# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()

router.register(r'essence', refviews.AmEssenceViewSet)
router.register(r'nature', refviews.AmNatureViewSet)
router.register(r'gestionbe', refviews.AmGestionbeViewSet)
router.register(r'naturebe', refviews.AmNaturebeViewSet)
router.register(r'objectifinit', refviews.AmObjectifInitViewSet)
router.register(r'conduite', refviews.AmConduiteViewSet)
router.register(r'topography', refviews.TopographyViewSet)


admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^api/v1/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', HomepageView.as_view()),
    url(r'^search/', include('haystack.urls')),

    url(r'^site/$',
        parcviews.SiteList.as_view(model=Site,
                                   paginate_by=10
                                   ),
        name='site_list'),

    url(r'^site/(?P<pk>\d+)$',
        DetailProtected.as_view(model=Site),
        name='site_detail'),

    url(r'^contact/$',
        contactviews.ContactList.as_view(model=Contact,
                                         paginate_by=10
                                         ),
        name='contact_list'),

    url(r'^contact/(?P<pk>\d+)$',
        DetailProtected.as_view(model=Contact),
        name='contact_detail'),

    #url(r'^contact/json/$',
    #contactviews.ContactJSONList.as_view(),
    #name='contact_json'),


    url(r'^map/$', ListProtected.as_view(model=Map,
                                         queryset=Map.objects.order_by("-pk").only('title'),
                                         ), name='map_list'),
    url(r'^map/new$', mapviews.MapNew.as_view(model=Map), name='map_new'),
    url(r'^map/(?P<pk>\d+)$', DetailProtected.as_view(model=Map), name='map_detail'),
    url(r'^map/(?P<pk>\d+)/edit$', mapviews.MapEdit.as_view(model=Map), name='map_edit'),
    url(r'^map/(?P<pk>\d+)/json$', mapviews.map_json, name='map_json'),
    url(r'^map/(?P<pk>\d+)/kml21$', mapviews.map_kml, name='map_kml21'),
    url(r'^map/(?P<pk>\d+)/geojson$', mapviews.MapDetail.as_view(), name='map_geojson'),
    url(r'^map/(?P<pk>\d+)/geojsonp$', mapviews.MapDetail.as_view(), name='map_geojsonp'),
    #url(r'^map/(?P<pk>\d+)/geojsonpo$', mapviews.map_jsonp, name='map_geojsonp'),

    url(r'^parcel/(?P<pk>\d+)$', DetailProtected.as_view(model=Parcel), name='parcel_detail'),

    url(r'^parcel/new$',
        parcviews.ParcelNew.as_view(),
        name='parcel_new'),

    url(r'^parcel/$',
        parcviews.ParcelList.as_view(model=Parcel,
                                     paginate_by=10),
        name='parcel_list'),

    url(r'^parcel/json/$', parcviews.ParcelJSONList.as_view(), name='parcel_json'),
    url(r'^parcel/geojson$', GeoJSONLayerView.as_view(model=Parcel,
                                                      properties=['title'],
                                                      geometry_field='center'), name='parcel_geojson'),

    url(r'^block/$', parcviews.BlockList.as_view(model=Block), name='block_list'),
    url(r'^block/(?P<pk>\d+)$', parcviews.BlockDetail.as_view(), name='block_detail'),
    url(r'^block/(?P<pk>\d+)/import$', DetailProtected.as_view(model=Block,
                                                               template_name="parc/block_import.html"), name='block_import'),
    url(r'^block/(?P<pk>\d+)/edit$', parcviews.BlockEdit.as_view(), name='block_edit'),
    url(r'^block/new$', ListProtected.as_view(model=Block), name='block_new'),
    url(r'^block/geojson$', GeoJSONLayerView.as_view(model=Block,
                                                     geometry_field='center'), name='block_geojson'),

    url(r'^project/$', views.ProjetListView.as_view(), name='projet_list'),
    url(r'^project/(?P<pk>\d+)$', views.ProjetDetailView.as_view(), name='projet_detail'),
    url(r'^project/new$', ListProtected.as_view(model=Projet), name='projet_new'),
    url(r'^accounts/profile/$', 'sigafo.users.views.profile', name='profile'),
    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

sigafo/parc/models.py
# -*- coding: utf-8 -*-
#
# Copyright (c) 2014-2016 Rodolphe Quiédeville <rodolphe@quiedeville.org>
# Copyright (c) 2014-2016 Agroof <http://www.agroof.net/>
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
from random import random
import json
from django.db import transaction
from django.contrib.auth.models import User
from django.contrib.gis.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.gis.geos.point import Point
from django.core.urlresolvers import reverse
from django_hstore import hstore
from django_pgjson.fields import JsonField
from uuidfield import UUIDField
from sigafo.contact.models import Contact
from sigafo.osmboundary.models import Departement
from sigafo.ressources.models import Url
from sigafo.referentiel import models as refs
from sigafo.projet.models import Projet
from sigafo.utils.models import GeoHStoreManager

# Site

class Site(models.Model):
    """Un site designe un lieu commun
    """
    name = models.CharField(max_length=300)
    address = models.TextField(blank=True)

    commune = models.TextField(blank=True,
                               null=True)

    referent = models.ForeignKey(Contact,
                                 related_name='referent',
                                 blank=True, null=True)

    owner = models.ForeignKey(Contact,
                              related_name='owner',
                              blank=True, null=True)

    exploitant = models.ForeignKey(Contact,
                                   related_name='exploitant',
                                   blank=True, null=True)

    urls = models.ManyToManyField(Url, blank=True)
    comment = models.TextField(blank=True, null=True)

    #
    properties = JsonField(blank=True, null=True)

    # public info to display set on the map
    map_public_info = JsonField(blank=True, null=True)

    # updated by trigger
    nb_parcel = models.IntegerField(default=0)
    # updated by trigger
    nb_block = models.IntegerField(default=0)

    # Needed for some map, may be null
    projets = models.ManyToManyField(Projet, blank=True)

    center = models.PointField(blank=True, null=True)
    objects = models.GeoManager()

    def __unicode__(self):
        """
        The unicode method
        """
        return "%s" % (self.name)

    def __str__(self):
        """
        The string method
        """
        return "{}".format(self.name)

    def get_absolute_url(self):
        """
        Absolute url
        """
        return reverse('site_detail', args=[self.id])

    def get_parcels(self):
        return Parcel.objects.filter(site=self)

    def get_blocks(self):
        return Block.objects.filter(parcel__site=self)

    @property
    def approx_center(self):
        """
        Here return real center for now

        Return : Point
        """
        if self.center is None:
            return None
        else:
            randx = 0
            randy = 0
            return Point(x=self.center.x + randx,
                         y=self.center.y + randy)


    @property
    def center_lat(self):
        if self.center:
            return self.center.y
        else:
            return 0

    @property
    def center_lon(self):
        if self.center:
            return self.center.x
        else:
            return 0


# Emplacements
class Parcel(models.Model):
    """The client as consummer
    """
    site = models.ForeignKey(Site,
                             on_delete=models.PROTECT)
    name = models.CharField(max_length=50)

    # who owned the parcel
    owner = models.ForeignKey(Contact,
                              related_name='powner',
                              blank=True,
                              null=True)

    # who works on the parcel
    exploitant = models.ForeignKey(Contact,
                                   related_name='pexploit',
                                   blank=True, null=True)

    # in ha
    surface = models.FloatField(blank=True, null=True)

    # Type de systeme agricole
    systemprod = models.ForeignKey(refs.SystemProd,
                                   blank=True,
                                   null=True)

    # in ha
    altitude = models.FloatField(blank=True, null=True)

    # dispositifs experimental
    experimental_devices = models.ManyToManyField(refs.ExperimentalDevice,
                                                  blank=True)

    # in ha
    experimental = models.BooleanField(default=False)

    # Coordonnées GPS
    center = models.PointField(blank=True, null=True)
    polygon = models.PolygonField(blank=True, null=True)

    urls = models.ManyToManyField(Url, blank=True)

    # updated by trigger
    nb_block = models.IntegerField(default=0)
    # updated by triggers
    variables = hstore.DictionaryField(db_index=True,
                                       blank=True,
                                       null=True)

    # properties
    properties = JsonField(blank=True, null=True)

    # public info to display set on the map
    map_public_info = JsonField(blank=True, null=True)

    # icon_url
    icon_url = models.TextField(blank=True, null=True)    

    # who create the map
    creator = models.ForeignKey(User)

    comment = models.TextField(blank=True, null=True)
    objects = GeoHStoreManager()


    def __unicode__(self):
        """
        The unicode method
        """
        return "%s - %s" % (self.site.name, self.name)

    @property
    def departement(self):
        """The title
        """
        return Departement.objects.filter(polygon__contains=self.center)

    @property
    def title(self):
        """The title
        """
        return "%s" % (self.name)

    @property
    def anonymous_title(self):
        """An anonymous title
        """
        return u"parcel_{}".format(self.id)


    @property
    def approx_center(self):
        """
        Fake coordinate based on real coordinate

        Return : Point
        """
        if self.center is None:
            return None
        else:
            randx = (0.5 - random())/21
            randy = (0.5 - random())/21
            return Point(x=self.center.x + randx,
                         y=self.center.y + randy)

    def get_absolute_url(self):
        """Absolute url
        """
        return reverse('parcel_detail', args=[self.id])

    def get_blocks(self):
        return Block.objects.filter(parcel=self).only('name')

    @property
    def center_lat(self):
        if self.center:
            return self.center.y

    @property
    def center_lon(self):
        if self.center:
            return self.center.x


# Block, sous-ensemble de la parcelle
class Block(models.Model):
    """
    Un block est un emplacement geographique avec une activité
    """
    uuid = UUIDField(auto=True)
    parcel = models.ForeignKey(Parcel,
                               on_delete=models.PROTECT)

    name = models.CharField(max_length=300)

    surface = models.FloatField(blank=True, null=True)

    center = models.PointField(blank=True, null=True)

    date_debut = models.DateField(blank=True, null=True)
    date_fin = models.DateField(blank=True, null=True)

    year_start = models.PositiveSmallIntegerField(blank=True, null=True)
    year_stop = models.PositiveSmallIntegerField(blank=True, null=True)

    # maps
    map_ids = ArrayField(models.IntegerField(),
                         blank=True,
                         null=True)

    # usage
    # referentiel
    usage = models.CharField(max_length=300, blank=True)

    # projets
    projets = models.ManyToManyField(Projet, blank=True)

    urls = models.ManyToManyField(Url,
                                  blank=True)

    comment = models.TextField(blank=True, null=True)
    variables = hstore.DictionaryField(db_index=True, blank=True, null=True)
    import_initial = hstore.DictionaryField(db_index=True, blank=True, null=True)

    #
    topography = models.ForeignKey(refs.Topography,
                                   blank=True,
                                   null=True)

    classph    = models.ForeignKey(refs.ClassePH, blank=True, null=True)
    classprof  = models.ForeignKey(refs.ClasseProfondeur, blank=True, null=True)
    classhumid = models.ForeignKey(refs.ClasseHumidity, blank=True, null=True)

    # Production vegetales annuelles
    prod_veg_an = models.TextField(blank=True,
                                   null=True)

    # Production vegetales perennes
    prod_veg_per = models.TextField(blank=True,
                                    null=True)

    # Production animale
    prod_animal = models.TextField(blank=True,
                                   null=True)

    # Nature
    nature = models.ManyToManyField(refs.NatureBlock,
                                    blank=True)

    # Façon culturale
    tillages = models.ManyToManyField(refs.Tillage,
                                      blank=True)

    # Fertilisation
    fertilisations = models.ManyToManyField(refs.Fertilisation,
                                            blank=True)

    # Traitement phytosanitaire
    traitphytos = models.ManyToManyField(refs.TraitPhyto,
                                         blank=True)

    # Mode de conduite
    conduites = models.ManyToManyField(refs.ModeConduite,
                                       blank=True)


    #

sigafo/parc/templates/parc/block_detail.html
{% extends "base.html" %}{% load leaflet_tags %}{% load geojson_tags %}
{% load i18n %}{% load compress %}
{% block title %} : {{object.name}}{% endblock %}
{% block pagetitle %}{% trans "Bloc" %} : {{object.name}}{% endblock %}
{% block rssnavbar %}<a href="events/feed/"><img id="rssicon" src="{{STATIC_URL}}img/rss_blue-32.png" /></a>{% endblock %}
{% block content %}
<div class="row">
<div class="col-md-3">
  <h3>{{object.name}}</h3>
  <div class="well">
    <ul>
      <li>
        {% trans "Site" %} : <a href="{{object.parcel.site.get_absolute_url}}">{{object.parcel.site.name}}</a>
      </li>
      <li>
        {% trans "Parcel" %} : <a href="{{object.parcel.get_absolute_url}}">{{object.parcel.name}}</a>
      </li>
      <li>
      {% trans "Exploitant" %} :
      <a href="{{object.parcel.site.exploitant.get_absolute_url}}">
      {{object.parcel.site.exploitant|default:''}}</a>
      </li>
      <li>{% trans "Surface" %} : {{object.surface|default:''}}</li>
    </ul>
  </div>
  <div>
    <ul>
      <li>
        {% trans "Start on" %} : {{object.annee_debut}}
      </li>
    </ul>
  </div>
  <div class="well wellul">
    <ul>
      <li>{% trans "PH" %} : {{object.classph|default:''}}</li>
      <li>{% trans "Humidity" %} : {{object.classhumid|default:''}}</li>
      <li>{% trans "Profondeur" %} : {{object.classprof|default:''}}</li>
      <li>{% trans "Texture" %} : {{object.texture|default:''}}</li>
    </ul>
  </div>

  {% if user.is_staff %}
  <hr />
  {% trans "Données imports" %} : <a href="{{object.get_absolute_url}}/import">import</a>
  {% endif %}

</div>

<div class="col-md-7">

  <div>{{object.prod_veg_an}}</div>
  
    <table class="table table-condensed">
    <thead>
      <tr>
        <th>{% trans "Amenagements" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for amg in amgs %}
      <tr>
        <td>
          <span>{{amg.name}}</span>
          <span class="badge">{{amg.localisation}}</span>
          <span class="badge">{{amg.quality}}</span>
          <span class="badge">{{amg.proportion}}</span>
          
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>{% trans "Observations" %}</th>
      </tr>
    </thead>
    <tbody>
      {% for obs in object.get_observations %}
      <tr>
        <td>
          <span class="badge">{{obs.author}}</span> {{obs.observation}}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>

<div class="col-md-2">

  <div>
    {% if perms.parc.edit_block %}
    <p>
    <a href="{% url 'block_edit' pk=object.id %}" class="btn btn-primary btn-block">{% trans "Edit block" %}</a>
    </p>
    {% endif %}
  </div>


  
<div>
  
    <table class="table table-striped">
      <thead>
        <tr>
          <th>{% trans "Projects" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for projet in object.projets.all %}
        <tr>
          <td><a href="{% url 'projet_detail' pk=projet.id %}">{{projet.name}}</a></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>


  </div>

</div>
{% endblock %}

sigafo/parc/templates/parc/block_edit.html
{% extends "base.html" %}
{% load i18n %}{% load compress %}{% load crispy_forms_tags %}
{% block content %}
<div class="row">
<div class="col-md-8">
    {% crispy form %}
  </div>

  <div class="col-md-4">
  <div>
    
  </div>
  
  </div>
</div>
{% endblock %}

sigafo/parc/templates/parc/block_feed_description.html
<p>{{item.create_on}} {{item.create_by}}</p>
<ul>

<li>{{item.name}}</li>
<li>{{item.tag_regex}}</li>
</ul>
<p>
Apply on node : {{item.node_applied}}, way : {{item.way_applied}},
relation : {{item.relation_applied}}
</p>
<p>
Apply when create : {{item.create_applied}}, modify :
{{item.modify_applied}}, delete : {{item.delete_applied}}
</p<

sigafo/parc/templates/parc/block_form.html
{% extends "base.html" %}
{% load i18n %}{% load crispy_forms_tags %}
{% block content %}
<div class="row">    
  <div class="col-md-8">


    {{ form.non_field_errors }}
    {{ form.field_errors }}
    {{ form.errors }}

    
    {% crispy form %}
  </div>

  <div class="col-md-4">

    <div class="panel panel-info">
      <div class="panel-heading">{% trans "New map" %}</div>
      <div class="panel-body">Création d'une nouvelle carte.
      </div>
      </div>
  </div>

  </div>
{% endblock %}

sigafo/parc/templates/parc/block_import.html
{% extends "base.html" %}
{% load i18n %}{% load compress %}
{% block title %} : {{object.name}}{% endblock %}
{% block pagetitle %}{% trans "Alert" %} : {{object.name}}{% endblock %}
{% block rssnavbar %}<a href="events/feed/"><img id="rssicon" src="{{STATIC_URL}}img/rss_blue-32.png" /></a>{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-2">
    <h3>{{object.name}}</h3>
  <div class="well">
    <ul>
        <li>
        {% trans "Site" %} : <a href="{{object.parcel.site.get_absolute_url}}">{{object.parcel.site.name}}</a>
        </li>
        <li>
        {% trans "Parcel" %} : <a href="{{object.parcel.get_absolute_url}}">{{object.parcel.name}}</a>
        </li>
        <li>
        {% trans "Exploitant" %} : <a href="{{object.parcel.site.exploitant.get_absolute_url}}">{{object.parcel.site.exploitant}}</a>
        </li>
        <li>
        {% trans "Usage" %} : <a href="{{object.domain.get_absolute_url}}">{{object.usage}}</a>
        </li>
        <li>
        {% trans "Start on" %} : {{object.date_debut}}
        </li>
    </div>

  </div>

  <div class="col-md-10">
    <table class="table table-condensed">
      <thead>
        <tr>
          <th></th>
          <th>{% trans "Initial datas" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for key,val in object.import_initial.items %}
        <tr>
          <td>{{key}}</td><td>{{val}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>        
  </div>
  
  </div>
  </div>

{% endblock %}

sigafo/parc/templates/parc/block_list.html
{% extends "base.html" %}
{% load i18n %}
{% block rssnavbar %}<a href="feed/"><img id="rssicon" src="{{STATIC_URL}}img/rss_blue-32.png" /></a>{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-10">
    <h3>{% trans "Blocks" %}</h3>
    {% include "pager.html" %}
    <table class="table table-striped">
      <thead>
	<tr>
	  <th>{% trans "Name" %}</th>
      <th>{% trans "Surface" %}</th>
      <th>{% trans "Amgnt" %}</th>
	</tr>
      </thead>
      <tbody>
        {% for block in object_list %}
        <tr>
          <td><a
            href="{{block.get_absolute_url}}">{{block.parcel.site.name}}
            - {{block.parcel.name}} - {{block.name}}</a></td>
          <td>{{block.surface}}</a></td>
          <td>{{block.nb_amg}}</a></td>          
        </tr>
        {% endfor %}
      </tbody>
    </table>      
  </div>

  <div class="col-md-2">
    <div>
      {% include "buttons.html" %}
    </div>
    
  </div>
</div>
{% endblock %}

sigafo/parc/templates/parc/block_new.html
{% extends "base.html" %}
{% load i18n %}{% load compress %}{% load crispy_forms_tags %}
{% block content %}
<div class="row">
  <div class="col-md-8">
    <h1>{% trans "New alert" %}</h1>
    <hr/>
    {% crispy form %}
  </div>

  <div class="col-md-4">
    <div>

    </div>

  </div>
</div>
{% endblock %}

sigafo/parc/templates/parc/parcel_detail.html
{% extends "base.html" %}{% load leaflet_tags %}{% load geojson_tags %}
{% load i18n %}{% load compress %}
{% block title %} : {{object.name}}{% endblock %}
{% block pagetitle %}{% trans "Alert" %} : {{object.name}}{% endblock %}
{% block rssnavbar %}<a href="events/feed/"><img id="rssicon" src="{{STATIC_URL}}img/rss_blue-32.png" /></a>{% endblock %}
{% block content %}
<div class="row">
<div class="col-md-4">
  <h3>{{object.name}}</h3>
<div class="well">
  <ul>
    <li>
    {% trans "Site" %} : <a href="{{object.site.get_absolute_url}}">{{object.site}}</a>
    </li>
    <li>
    {% trans "Exploitant" %} : <a href="{{object.exploitant.get_absolute_url}}">{{object.exploitant}}</a>
    </li>
    <li>
    {% trans "Usage" %} : <a href="{{object.domain.get_absolute_url}}">{{object.usage}}</a>
    </li>
    <li>
    {% trans "Surface" %} : {{object.surface|default:''}}
    </li>
    <li>
    {% trans "Altitude" %} : {{object.altitude|default:''}}
    </li>
    <li>
    {% trans "Lon / Lat" %} :
    <a target="_blank" href="http://www.openstreetmap.org/#map=12/{{object.center.y}}/{{object.center.x}}">
    {{object.center.x}}, {{object.center.y}}</a>
    </li>
    <li>
    {% trans "Geozone" %} : <a href="{{object.geozone.get_absolute_url}}">{{object.geozone}}</a>
    </li>
    <li>
    {% trans "Start on" %} : {{object.date_debut}}
    </li>
    </div>

    {% leaflet_map "alert_detail" callback="main_map_init" %}
    {% if object.description %}
    <hr/>

    <div>
    <div class="alert alert-info">
      {{object.description}}
    </div>
    </div>
    {% endif %}
    </div>

    <div class="col-md-6">
      <table class="table table-condensed">
        <thead>
          <tr>
            <th>{% trans "Blocks" %}</th>
          </tr>
        </thead>
        <tbody>
          {% for block in object.get_blocks %}
          <tr>
            <td><a href="{{block.get_absolute_url}}">{{block.name}}</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
  </div>

  <div class="col-md-2">
    {% if perms.parc.add_block %}
    <p>
    <a href="{% url 'block_new' %}" class="btn btn-primary btn-block">{% trans "Add block" %}</a>
    </p>
    {% endif %}
  </div>

</div>
{% endblock %}

sigafo/parc/templates/parc/parcel_list.html
{% extends "base.html" %}
{% load i18n %}
{% block jsheaders %}<script src="{{STATIC_URL}}js/api.js"></script>{% endblock %}
{% block body %}<body onload="parcel_list({% url "parcel_json" %}>{% endblock %}
{% block content %}
<div class="row">
  <div class="col-md-10">
    {% include "pager.html" %}
    <table class="table table-striped">
      <thead>
    <tr>
      <th>{% trans "Site" %}</th>
      <th>{% trans "Name" %}</th>
      <th>{% trans "System" %}</th>
      <th>{% trans "Blocks" %}</th>
      <th>{% trans "Experimental" %}</th>
    </tr>
      </thead>
      <tbody>
        {% for parcel in object_list %}
        <tr>
          <td>
            <a href="{{parcel.site.get_absolute_url}}">{{parcel.site.name}}</a>

          </td>
          <td><a href="{{parcel.get_absolute_url}}">{{parcel.name}}</a></td>
          <td>{{parcel.systemprod.name}}</td>
          <td>{% if parcel.nb_block > 0 %}{{parcel.nb_block}}{% endif %}</a></td>
          <td>{{parcel.experimental}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="col-md-2">
    <div>
      <h3>{% trans "Parcels" %}</h3>
      {% include "buttons.html" %}
    </div>

  </div>
</div>
{% endblock %}

sigafo/parc/templates/parc/parcel_new.html
{% extends "base.html" %}
{% load i18n %}{% load crispy_forms_tags %}
{% block content %}
<div class="row">    
  <div class="col-md-8">


    {{ form.non_field_errors }}
    {{ form.field_errors }}
    {{ form.errors }}

    
    {% crispy form %}
  </div>
  
  <div class="col-md-4">
    <div class="panel panel-info">
      <div class="panel-heading">{% trans "New parcel" %}</div>
      <div class="panel-body">Création d'une nouvelle parcelle.</div>
    </div>
    <div class="panel panel-info">
      <div class="panel-heading">{% trans "Contact" %}</div>
      <div class="panel-body">
        <a href="{% url 'parcel_new' %}" class="btn btn-primary btn-block">{% trans "Ajout comme propriétaire" %}</a>               
      </div>
    </div>
  </div>
</div>
{% endblock %}

sigafo/parc/templates/parc/site_list.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
<div class="row">
  <div class="col-md-10">
    <h3>{% trans "Sites" %}</h3>
    {% include "pager.html" %}
    <table class="table table-striped">
      <thead>
	<tr>
	  <th>{% trans "Name" %}</th>
	  <th>{% trans "Owner" %}</th>
	</tr>
      </thead>
      <tbody>
	{% for site in object_list %}
	<tr>
	  <td><a href="{{site.get_absolute_url}}">{{site.name}}</a></td>
	  <td><a href="{{site.owner.get_absolute_url}}">{{site.owner}}</a></td>
	</tr>
	{% endfor %}
      </tbody>
    </table>      
  </div>

  <div class="col-md-2">
    <div>
          {% include "buttons.html" %}
    </div>

  </div>
</div>
{% endblock %}